### ISSUE TITLE
DNA 2.0 freezes

### ISSUE THREAD

**Issue by grandee99** [leifeld/dna#246] opened 2022-07-12 14:23 UTC
Dear dna community, 

after a couple weeks of using DNA 2.0, the program continuously freezes. I have tried to split my data into two different databases but it still freezes. I have also tried to work instead with the new update but unfortunately, it doesn't recognize my statements so I can"t just continue in the new version. Since I am in the middle of my data, any help would be appreciated. 

Greetings, Nicola

**Comment by leifeld** [comment] 2022-07-12 14:53
Hi Nicola. If you send me your database by email, I'm happy to take a look and see if I can find out what's wrong. You can find my email address [here](https://www.philipleifeld.com/contact/).

**Comment by leifeld** [comment] 2022-07-12 16:20
All right, I have taken a look at your file. Thanks for sending it to me.

I think the problem is that one of the documents you added is very long, in fact 73,000 lines of text. That's like a long book. The document in question is ID 7, dated 20 July 2016.

It does not produce an error message. I can load it just fine on my system. But this document in particular loads very slowly. Maybe it appears like DNA is frozen because of how slowly it reacts.

The reason is that DNA 2 couldn't handle long documents very well. DNA 3 shouldn't have those problems. It still takes a few seconds to load the long document, but it does react well after those few initial seconds.

Is there a particular reason you are using DNA 2 and not DNA 3? E.g., do you need rDNA for it soon? If you don't care about rDNA so much and you are happy with the analysis functions in visone or basic network analysis in R, you should be able to import your data into a new DNA 3 database and continue working there. I think this should fix your problem. I have just imported the data into a new DNA 3 database for you and will send it to you by email. You can try out which version you prefer.

If you do require rDNA for your work soon, I would recommend splitting your documents into smaller chunks and saving them as separate documents. Something like `Document 1, part 1` for the first 10,000 lines and so on.

But even if you continue using DNA 3, I would still recommend subdividing any new documents into smaller separate documents in order not to have to wait several seconds each time to load the respective document. Maybe not 10,000, but definitely fewer lines than those 73,000.

Let me know what you think.

**Comment by leifeld** [comment] 2022-07-12 17:10
Closing the issue because the problem was resolved by deleting the longest document (and potentially replacing it by shorter partial documents).

**Closed by leifeld** 2022-07-12 17:10 UTC
Labels: bug, question, DNA data structures, version 2.0
