### ISSUE TITLE
Problems when import files from directory

### ISSUE THREAD

**Issue by lijush** [leifeld/dna#254] opened 2022-12-23 16:10 UTC
When I use DNA 3.0.8 to import text files from a folder, two problems arise:
1. The Regex of Date/Time works well in the window of "Import text files"(for example, 01.03.2018, 01.03.2019), but after the importing process, the date becomes the time when I import those files (for example, 2022-12-23).
2.  The Regex of Source **(?<=.+?-)[a-zA-Z]+(?=-[A-Z0-9\(\)]+\.txt)** does not work.
All these files' names follow the format DD.MM.YYYY - Author - Source - TYPE.txt

<img width="435" alt="aaa" src="https://user-images.githubusercontent.com/26033215/209364681-aafef21e-b1a1-47d2-81a4-3b764c33d7f9.png">
<img width="755" alt="bbb" src="https://user-images.githubusercontent.com/26033215/209364696-210004f5-e4eb-4187-9f02-bea42c002aee.png">

I would be grateful if you could help me with these two problems. And thank you for your continuous efforts to improve DNA.

**Comment by leifeld** [comment] 2022-12-24 10:11
I think this is mostly a duplicate of #239. See there for additional advice. I fixed this recently, and the new version will be forthcoming in a few weeks. I will [attach a test version here](https://github.com/leifeld/dna/files/10298352/dna-3.0.9.e1.zip). Can you let me know if this new version fixes your problem? Thanks.

**Comment by leifeld** [comment] 2022-12-24 10:29
PS: I think you could use something like this to parse the source in your case:
`(?<=\D - ).+(?= - .+\.txt)`

**Comment by lijush** [comment] 2022-12-24 11:46
This new version and the Regex works well. Thank you!

**Closed** 2022-12-24 12:05 UTC
Labels: bug, duplicate, DNA GUI, version 3.0
