### ISSUE TITLE
Statement details box bug

### ISSUE THREAD

**Issue by Laurencebl1** [leifeld/dna#243] opened 2022-07-03 14:55 UTC
Hi. I have this new issue since today. The Statement details window is bug. I try to change the name of the organisation of a statement that I have coded in the past. I am able to make the change but when I save nothing happens. If I click Cancel or the x, nothing happens too. I am however able to refresh the DNA but the window still remains there. There is no error message that is shown in the bottom right in DNA. My only solution is then to close the software completely and open it again. This has just happened to me 3 times. I am able to change one or two organization then at the third time, the window does not leave any more.

I'm on DNA 3.0.6 3 , MacOS Monteray, Java version is Temurin 16.0.2 + 7

**Comment by leifeld** [comment] 2022-07-04 13:29
Thanks. Probably the same as #237. I'd like to fix this, but can't really see under what conditions it happens. I need some sort of pattern to look out for, or something I can use to reproduce the problem. @TimHenrichsen Can you confirm this with the same database and with with window decoration switched on?

**Comment by TimHenrichsen** [comment] 2022-07-04 15:40
I tested it but couldn't reproduce the problem, unfortunately. But I also encountered the same issue as #237 (not today but during the summer school course). I also haven't found any pattern that would explain under what conditions this bug appears but I'm also guessing that the problem of this issue and 237 might be related somehow.. @Laurencebl1 could you please update to DNA 3.0.8 and check if this problem still occurs?

**Comment by leifeld** [comment] 2022-07-04 16:53
Thanks, both! For now, let's assume the problem has gone away by updating to DNA 3.0.8. I will close the issue here. But if it happens again, can you please re-open this issue or comment here again, in case the problem persists?

**Closed by leifeld** 2022-07-04 16:53 UTC
Labels: bug, DNA GUI, version 3.0
