### ISSUE TITLE
DNA3: Cannot exclude sources when exporting data

### ISSUE THREAD

**Issue by SofieRoehrig** [leifeld/dna#251] opened 2022-10-11 10:32 UTC
In DNA3, I cannot exclude sources when exporting data. I get the following errors and warnings:

<html>
<body>

2022-10-11T12:04:55.153732600 | [SQL] Failed to retrieve statements. | Attempted to retrieve a set of 0 statements from the database, but something went wrong. | logger.LogEvent 	at sql.Sql.getStatements(Sql.java:3277) 	at export.Exporter.loadData(Exporter.java:323) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | java.sql.SQLSyntaxErrorException: Unknown column 'EurActiv.com' in 'where clause' 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) 	at sql.Sql.getStatements(Sql.java:3185) 	at export.Exporter.loadData(Exporter.java:323) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | 3
-- | -- | -- | -- | -- | --

</body>
</html>

<html>
<body>

2022-10-11T12:04:55.157948100 | Uncaught exception. | An uncaught exception occurred. This is most likely a bug. Please open a new issue at https://github.com/leifeld/dna/issues/ and paste the log event stack trace and the exception stack trace there as part of your error description, along with details of what happened and under what circumstances. Thank you. | logger.LogEvent 	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:83) 	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055) 	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050) 	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1997) | java.lang.NullPointerException 	at export.Exporter.loadData(Exporter.java:335) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | 3
-- | -- | -- | -- | -- | --

</body>
</html>

<html>
<body>

2022-10-11T12:05:30.613971300 | [SQL] Failed to retrieve statements. | Attempted to retrieve a set of 0 statements from the database, but something went wrong. | logger.LogEvent 	at sql.Sql.getStatements(Sql.java:3277) 	at export.Exporter.loadData(Exporter.java:323) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'France Presse', 'Agence France-Presse) AND STATEMENTS.StatementTypeId IN (1) ORD' at line 1 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) 	at sql.Sql.getStatements(Sql.java:3185) 	at export.Exporter.loadData(Exporter.java:323) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | 3
-- | -- | -- | -- | -- | --

</body>
</html>

<html>
<body>

2022-10-11T12:05:30.614956700 | Uncaught exception. | An uncaught exception occurred. This is most likely a bug. Please open a new issue at https://github.com/leifeld/dna/issues/ and paste the log event stack trace and the exception stack trace there as part of your error description, along with details of what happened and under what circumstances. Thank you. | logger.LogEvent 	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:83) 	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055) 	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050) 	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1997) | java.lang.NullPointerException 	at export.Exporter.loadData(Exporter.java:335) 	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1187) 	at java.base/java.lang.Thread.run(Thread.java:829) | 3
-- | -- | -- | -- | -- | --

</body>
</html>

**Comment by leifeld** [comment] 2022-10-15 17:31
Hi there. I haven't been able to reproduce the problem with the sample dataset. If you could send me a dataset I can use to reproduce the error with, I should be able to fix it. If possible by email. Many thanks in advance.

**Comment by leifeld** [comment] 2022-12-15 00:21
@TimHenrichsen Can you reproduce this error? I couldn't with the sample dataset. Thanks.

**Comment by TimHenrichsen** [comment] 2022-12-15 10:00
I couldn't reproduce it with the sample dataset either but I was able to reproduce the error with a different dataset. I'll send you an e-mail in a few minutes.

**Comment by leifeld** [comment] 2022-12-15 10:48
Thanks, @TimHenrichsen for sending an example by email. I have found and fixed the bug and will commit it in a minute and close this issue.

**Closed** 2022-12-15 10:50 UTC
Labels: bug, DNA GUI, version 3.0
