### ISSUE TITLE
export

### ISSUE THREAD

**Issue by geeklight01** [leifeld/dna#97] opened 2017-03-10 16:56 UTC
I am working with the new DNA version and I have the 3 following questions:

- When I export my DNA into visone I got a node named "1". I don't understand why. Moreover when I export my DNA file in .csv I get a column without title, meaning that I have an adjacency matrix (n x n+1). I believe that this is the reason why I have a node which is named "1" in visone. How can I fix that?

- When I export my DNA file into Visone (two mode network), I cannot see clearly (the color is the same, even after manipulation in Visone) whether an actor agrees or disagrees with a statement.

- Can you please explain what's the purpose of the agreement qualifier and how it does exactly work.

Thanks in advance!

**Comment by leifeld** [comment] 2017-03-14 00:01
> When I export my DNA into visone I got a node named "1". I don't understand why.

Do you have a value in the first or second variable that is "1"? If not, I haven't seen this before. What DNA version are you using?

> Moreover when I export my DNA file in .csv I get a column without title, meaning that I have an adjacency matrix (n x n+1). I believe that this is the reason why I have a node which is named "1" in visone. How can I fix that?

The column without a title represents statements where the variable of interest is empty (i.e., literally ""). But if you are exporting a square adjacency matrix, the empty string should be both in the rows and columns. Can you confirm? I realize that it's not ideal to have empty values included in the export. So I'll work on this to remove that row/column when I get a chance. As a workaround, just delete the entry from the CSV file manually for now.

> When I export my DNA file into Visone (two mode network), I cannot see clearly (the color is the same, even after manipulation in Visone) whether an actor agrees or disagrees with a statement.

This depends on the qualifier aggregation rule (see below).

> Can you please explain what's the purpose of the agreement qualifier and how it does exactly work.

The qualifier variable can be something like a sentiment or intensity. For example, an actor could agree or disagree to a concept (i.e., a binary qualifier) or agree with a certain intensity on a scale from -5 to +5 (i.e., an integer qualifier). The qualifier aggregation setting determines what DNA does with this qualifier variable. In the simplest case, the qualifier is ignored, in which case positive and negative ties are all treated equally (i.e., they receive a black color when exported to visone). You can also choose other settings, and these settings determine what is done exactly. You should check the help button in the lower left corner of the export window and then move the mouse to the setting in order to get more detailed help.

**Comment by leifeld** [comment] 2017-03-16 09:43
Possible duplicate of #95

**Comment by leifeld** [comment] 2017-04-04 19:28
Closed in commits 9d1c531d423e28397a378115aa09df1000fe7e05 and 423fd397cac6207e104e938a4f7da6dfd133bbe2.

**Closed by leifeld** 2017-04-04 19:28 UTC
Labels: enhancement, question, version 2.0
